### PR TITLE
add meshviewer links to nodes.html

### PR DESCRIPTION
**Pull request by belzebub40k**
Add links to Meshviewer on the `/nodes` page.

### CODE REVIEW

**Comment by blocktrron** [comment]
Hi, sorry for responding so late - i was not notified about your PW somehow :confused: 

I really like this idea. Do you plan to rebase your changes?

**Comment by belzebub40k** [comment]
Yes, I'll rebase it onto the current master.

**Comment by belzebub40k** [comment]
@blocktrron  I rebased the branch and added some addition changes. Updated nodes template with some basic CSS for better readability and the possibility to filter the overview by mesh_id.

**Comment by blocktrron** [comment]
Description of the config key is missing in the docs. I will to the fixup for that.

Thanks!

**Pull request merged**
